eapp/urls.py
from django.urls import path 
from .import views
from django.contrib.auth import views as auth
# from eapp.views import index




urlpatterns = [
    # path('',index.as_view(), name='index'),
    path('',views.index , name = 'index'),

    path('base/',views.base , name = 'base'),
    path('login/',views.login , name = 'login'),
    path('logout/',auth.LogoutView.as_view(template_name = 'eapp_temp/index.html'),name="logout"),
    path('register/',views.register , name = 'register'),
    path('adminhome/',views.adminhome , name = 'adminhome'),
    path('remove_cart/<str:cid>',views.remove_cart , name = 'remove_cart'),
    path('addcategory/',views.admin_add_category , name = 'admin_add_category'),
    path('addproduct/',views.admin_add_product , name = 'admin_add_product'),
    path('userhome/',views.userhome , name = 'userhome'),
    path('userhome/<str:name>',views.productview,name="userhome"),
    path('userhome/<str:cname>/<str:pname>',views.productdetails,name="productdetails"),
    path('addtocart/',views.add_to_cart , name = 'addtocart'),
    path('cart_page/',views.cart_page , name = 'cart_page'),
    path('userprofile/',views.userprofile , name = 'userprofile'),
    path('order_view/',views.order_view , name = 'order_view'),
    path('place_order/',views.place_order , name = 'place_order'),









]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('django.contrib.auth.urls')),
    path('',include('eapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

eapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
import os

# Create your models here.
def getFileName(request,filename):
    now_time = datetime.datetime.now().strftime("%Y%m%d%H:%M:%S")
    new_filename = "%s%s"%(now_time,filename)
    return os.path.join('uploads/',new_filename)

class Category(models.Model):
    name = models.CharField(max_length=150,null =False,blank = True)
    image = models.ImageField( upload_to=getFileName,null =False,blank = True)
    description = models.TextField(max_length=400,null =False,blank = True)
    status = models.BooleanField(default = False,help_text ="0-show,1-hidden")
    created_at = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    Category = models.ForeignKey("Category", on_delete=models.CASCADE)
    name = models.CharField(max_length=150,null =False,blank = True)
    vendor = models.CharField(max_length=150,null =False,blank = True)
    Product_image = models.ImageField( upload_to=getFileName,null =False,blank = True)
    quantity = models.IntegerField(null =False,blank = True)
    price = models.IntegerField(null =False,blank = True)
    description = models.TextField(max_length=400,null =False,blank = True)
    status = models.BooleanField(default = False,help_text ="0-show,1-hidden")
    created_at = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return self.name

class Cart(models.Model):
  user=models.ForeignKey(User,on_delete=models.CASCADE)
  product=models.ForeignKey(Product,on_delete=models.CASCADE)
  product_qty=models.IntegerField(null=False,blank=False)
  created_at=models.DateTimeField(auto_now_add=True)


  @property
  def total_cost(self):
    return self.product_qty * self.product.price

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False)
    status = models.CharField(max_length=100, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)

templates/eapp_temp/add_category.html
{% extends 'base.html' %}

{% block title %}Book Detail{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'adminhome' %}">Admin Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
</nav>
<br>

<center>
    <h1>Add CAt</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_title">Title</label>
        {{ form.name }}
        <br><br>
        <label for="id_description">Image</label>
        {{ form.image }}
        <br><br>
        <label for="id_image">Description</label>
        {{ form.description }}
        <br><br> 
        <input type="submit" value="Submit">
    </form>
</center>

{% endblock %}

templates/eapp_temp/add_product.html
{% extends 'base.html' %}

{% block title %}Add Product{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'adminhome' %}">Admin Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
</nav>
<br>

<center>
    <h1>Add Product</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_title">Product Category</label>
        {{ form.Category }}
        <br><br>
        <label for="id_title">name</label>
        {{ form.name }}
        <br><br>
        <label for="id_title">Vendor</label>
        {{ form.vendor }}
        <br><br>
        <label for="id_description">Image</label>
        {{ form.Product_image }}
        <br><br>
        <label for="id_image">Quantity</label>
        {{ form.quantity }}
        <br><br>
        <label for="id_image">Price</label>
        {{ form.price }}
        <br><br>
        <label for="id_image">Description</label>
        {{ form.description }}
        <br><br>
 
        <input type="submit" value="Submit">
    </form>
</center>
{% endblock %}

templates/eapp_temp/adminhome.html
{% extends 'base.html' %}

{% block title %}Book Detail{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Admin home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  

    {% if user.is_authenticated %}
    <li class="nav-item" style="margin-left: 1000px;">
        <a class="nav-link text-white" href="{% url 'admin_add_category' %}">Add Category</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'admin_add_product' %}">Add Product</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'logout' %}">logout</a>
    </li>

    {% endif%}
</nav>
<br>

<center>
    <h1>Admin Home</h1>

</center>
{% endblock %}

templates/eapp_temp/index.html
{% extends 'base.html' %}

{% block title %}Post{% endblock %}

{% block content %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Ecommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="margin-left: 1250px;">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active ">
          <a class="nav-link" href="{% url 'login' %}">Login <span class="sr-only"></span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'register' %}">Register <span class="sr-only"></span></a>
          </li>
  
  </nav><br>
   <center>  <h1>Buy any products</h1></center>

<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">Categories</h4>
        <hr style="border-color:#b8bfc2;">
      </div>
      {% for prod in category %}
      <div class="col-md-4 col-lg-3">
        <div class="card my-3">
          <img src="{{ prod.image.url }}" class="card-img-top" alt="Categories">
          <a href="{% url 'userhome' prod.name %}">


            <div class="card-body">
              <h5 class="card-title text-primary">{{ prod.name }}</h5>
              <p class="card-text">{{ prod.description }}</p>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>


  
 
{% endblock %}

templates/eapp_temp/login.html
{% extends 'base.html'%}

{% block title %}Login {% endblock title %}


{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Login</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
  </nav><br>
  <center>

    <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark btn-sm">Login</button>
        </form>
  </center>

{% endblock content %}

templates/eapp_temp/orderview.html
{% extends 'base.html' %}
{% block title %}Orders {% endblock title %}

{% block content %}
<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">My Orders</h4>
        <hr style="border-color:#b8bfc2;">
      </div>
      <div class="col-12">
        {% if orders %}
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Order ID</th>
              <th scope="col">Product</th>
              <th scope="col">Quantity</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
            <tr>
              <th scope="row">{{ order.id }}</th>
              <td>{{ order.product.name }}</td>
              <td>{{ order.quantity }}</td>
              <td>{{ order.status }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>No orders found.</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/eapp_temp/productdetails.html
{% extends 'base.html' %}
{% block title %}
ShopKart | Online Shopping
{% endblock title %}

{% block content %}
<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <h4 class="mb-3">  {{products | upper}}</h4>
              <hr style="border-color:#b8bfc2;">
          </div>
          <div class="col-4 my-3 pic-box">
              <div class="hot"></div>
              <img src="{{products.Product_image.url}}"  class="card-image-top" alt="{{products}}">
          </div>
          <div class="col-8 my-3">
              <h5 class="text-success">{{products | upper}}</h5>
              <p>{{products.vendor}}</p>
              <p>{{products.description}}</p>
              <h5 class="my-2 text-primary">Price   : Rs.{{products.price}}</h5>
              <div>
                  {% if products.quantity > 0 %}
              
                  <input type="hidden" value="{{products.id}}" id="pid">

                  <p>
                      <div class="input-group" style="width:150px">
                          <button class="input-group-text bg-success text-light" id="btnMinus"><i class="fa fa-minus"></i></button>
                          <input type="text" name="qty" id="txtQty" value="1" class="form-control text-center">
                          <button class="input-group-text bg-success text-light" id="btnPlus"><i class="fa fa-plus"></i></button>
                      </div>
                  </p>
                  <button class="btn btn-primary" id="btnCart"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
                  {% else %}
                  <button class="btn btn-secondary" id="btnCart"><i class="fa fa-shopping-cart"></i> Out Of Stock</button>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
</section>

  <script>
    document.addEventListener("DOMContentLoaded", function(event) {
    const btnPlus = document.getElementById("btnPlus");
    const btnMinus = document.getElementById("btnMinus");
    const txtQty = document.getElementById("txtQty");
    const pid = document.getElementById("pid");
    const btnCart = document.getElementById("btnCart");

    btnPlus.addEventListener("click", function() {
      let qty = parseInt(txtQty.value, 10);
      qty = isNaN(qty) ? 0 : qty;
      //console.log(qty);
      if (qty < 10) {
        qty++;
        txtQty.value = qty;
      }
    });
  
    btnMinus.addEventListener("click", function() {
      let qty = parseInt(txtQty.value, 10);
      qty = isNaN(qty) ? 0 : qty;
      //console.log(qty);
      if (qty > 1) {
        qty--;
        txtQty.value = qty;
      }
    });

    btnCart.addEventListener("click", function() {
      let qty=parseInt(txtQty.value,10);
      qty=isNaN(qty)?0:qty;

      if(qty>0){
        let postObj = {
            'product_qty': qty,
            'pid': pid.value
        }
        //console.log(postObj);
        fetch("/addtocart/",{
          method: 'POST',
          credentials: 'same-origin',
          headers:{
              'Accept': 'application/json',
              'X-Requested-With': 'XMLHttpRequest',
              'X-CSRFToken': '{{ csrf_token }}',
          },
          body: JSON.stringify(postObj)
        }).then(response => {
	        return response.json();
        }).then(data => {
        	//console.log(data);
          alert(data['status']);
        });


      }else{
        alert("Please Enter The Quantity");
      }

  });
});
  




  </script>
  
 
{% endblock content %}

templates/eapp_temp/products.html
{% extends 'base.html' %}
{% block title %}
ShopKart | Online Shopping
{% endblock title %}

{% block content %}

<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">{{category_name}} Products</h4>
        <hr style="border-color:#b8bfc2;">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active">{{category_name}} Collections</li>
          </ol>
        </nav>
      </div>
      {% for prod in products %}
      <div class="col-md-4 col-lg-3">
        <div class="card my-3">
          <img src="{{prod.Product_image.url}}"  class="card-image-top" alt="Categories">
          <a href="{% url 'productdetails' category_name prod.name %}">

          <div class="card-body">
            <h5 class="card-title text-primary">{{ prod.name }}</h5>
            <p class="card-text">
              <span class="float-start oprice">Rs.{{ prod.price | stringformat:'d'}}</span>
            </p>
          </div>
        </a>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</section>
 
{% endblock content %}

templates/eapp_temp/register.html
{% extends 'base.html'%}

{% block title %}Register {% endblock title %}


{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Register</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
  </nav><br>
  <center>
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <label>sername: </label>
        {{form.username}}<br><br>
        <label>Email</label>
        {{form.email}}<br><br>
        <label>Phone Number</label>
        {{form.phone_number}}<br><br>
        <label>Password</label>
        {{form.password}}<br><br>
        <label>Confirm Password</label>
        {{form.password2}}<br><br>

        <input type="submit" value="submit">
    </form>
    

  </center>


{% endblock content %}

templates/eapp_temp/show_cart.html
{% extends 'base.html' %}

{% block title %}Show Cart{% endblock %}

{% block content %}

<section class="bg-light py-4 my-5" style="min-height:600px;">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h4 class="mb-3">Cart  Items</h4>
          <hr style="border-color:#b8bfc2;">
        </div>
      
        <table>
            <tr>
                <th>Image</th>
                <th>Product Name</th>
                <th>Unit</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Remove</th>
            </tr>
          

            {% for item in cart %}
           <tr>
              <td><img src="{{item.product.Product_image.url}}" height="75px" alt="{{item.product.name}}"></td>
              <td>{{item.product.name}}</td>
              <td>{{item.product.price | stringformat:'d'}}</td>
              <td>{{item.product_qty}}</td>
              <td class="amt">{{item.total_cost | stringformat:'d'}}</td>
              <td><a href="{% url 'remove_cart' item.id %}"  onclick="return confirm('Are you sure? to Remove')"  class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remove</a></td>


            </tr>
            {% endfor %}
            <tr>
              <td></td>
              <td></td>
              <th id="net"></th>
              <td><button class="btn btn-primary btn-sm">
                <i class="fa fa-check-circle"></i> Check Out
              </button></td>
            </tr>
           
        </table>
       
      </div>
      </div>
  </section>
{% endblock %}

templates/eapp_temp/user_profile.html
{% extends 'base.html'%}

{% block title %}Profile {% endblock title %}


{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">profile</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>  
  </nav><br>
  <center>
    <h3><u>User Profile</u></h3>
  
        <label>Name:</label>
        {{user.username}}<br>
        <label>Email:</label>
        {{user.email}}<br>


    

  </center>


{% endblock content %}

templates/eapp_temp/userhome.html
{% extends 'base.html' %}

{% block title %}Book Detail{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Userhome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {% if user.is_authenticated %}
  <li class="nav-item" style="margin-left: 1100px;">
    <a class="nav-link text-white" href="{% url 'cart_page' %}">Cart</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" href="{% url 'order_view' %}">Orders</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" href="{% url 'userprofile' %}">Profile</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" href="{% url 'logout' %}">logout</a>
  </li>
  {% endif %}
</nav>
<br>
<h5><i>Welcome   {{user.username}}</i></h5>

<section class="bg-light py-4 my-5" style="min-height:600px;">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h4 class="mb-3">Categories</h4>
        <hr style="border-color:#b8bfc2;">
      </div>
      {% for prod in category %}
      <div class="col-md-4 col-lg-3">
        <div class="card my-3">
          <img src="{{ prod.image.url }}" class="card-img-top" alt="Categories">
          <a href="{% url 'userhome' prod.name %}">


            <div class="card-body">
              <h5 class="card-title text-primary">{{ prod.name }}</h5>
              <p class="card-text">{{ prod.description }}</p>
            </div>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}